/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControllerTransaksi;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import model.Transaksi;

/**
 *
 * @author wildan
 */
public class ViewTransaksi extends javax.swing.JFrame {

    ControllerTransaksi ct;
    int idTransaksi;
    /**
     * Creates new form TransaksiView
     * @param id
     */
    public ViewTransaksi(int id) {
        initComponents();
        ct = new ControllerTransaksi(this);
        ct.getTransaksi(id);
        ct.getListBarang(id);
        idTransaksi = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_transaksi = new javax.swing.JLabel();
        tgl_label = new javax.swing.JLabel();
        tgl_value = new javax.swing.JLabel();
        penjual_label = new javax.swing.JLabel();
        penjual_value = new javax.swing.JLabel();
        pembeli_label = new javax.swing.JLabel();
        pembeli_value = new javax.swing.JLabel();
        list_barang_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_barang = new javax.swing.JList<>();
        harga_label = new javax.swing.JLabel();
        harga_value = new javax.swing.JLabel();
        metode_bayar_label = new javax.swing.JLabel();
        metode_bayar = new javax.swing.JComboBox<>();
        btn_batal = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_transaksi.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        label_transaksi.setText("TRANSAKSI");

        tgl_label.setText("Tanggal: ");

        tgl_value.setText("Tanggal");

        penjual_label.setText("Penjual:");

        penjual_value.setText("User");

        pembeli_label.setText("Pembeli:");

        pembeli_value.setText("User");

        list_barang_label.setText("List Barang");

        jScrollPane1.setViewportView(list_barang);

        harga_label.setText("Total Harga:");

        harga_value.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        harga_value.setText("Rp. 200.000");

        metode_bayar_label.setText("Metode Pembayaran");

        metode_bayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dana", "Ovo", "Shopeepay", "Gopay" }));

        btn_batal.setText("Batal");

        btn_bayar.setText("Bayar");
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(metode_bayar_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(penjual_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(penjual_value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pembeli_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pembeli_value))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tgl_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_transaksi)
                            .addComponent(tgl_value)))
                    .addComponent(list_barang_label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                            .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(metode_bayar, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(harga_label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(harga_value))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(label_transaksi)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgl_label)
                    .addComponent(tgl_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(penjual_label)
                    .addComponent(penjual_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pembeli_label)
                    .addComponent(pembeli_value))
                .addGap(40, 40, 40)
                .addComponent(list_barang_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga_label)
                    .addComponent(harga_value))
                .addGap(18, 18, 18)
                .addComponent(metode_bayar_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(metode_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_batal)
                    .addComponent(btn_bayar))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        ct.bayarTransaksi(idTransaksi);
    }//GEN-LAST:event_btn_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ViewTransaksi().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JLabel harga_label;
    private javax.swing.JLabel harga_value;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_transaksi;
    private javax.swing.JList<String> list_barang;
    private javax.swing.JLabel list_barang_label;
    private javax.swing.JComboBox<String> metode_bayar;
    private javax.swing.JLabel metode_bayar_label;
    private javax.swing.JLabel pembeli_label;
    private javax.swing.JLabel pembeli_value;
    private javax.swing.JLabel penjual_label;
    private javax.swing.JLabel penjual_value;
    private javax.swing.JLabel tgl_label;
    private javax.swing.JLabel tgl_value;
    // End of variables declaration//GEN-END:variables

    public JButton getBtn_batal() {
        return btn_batal;
    }

    public void setBtn_batal(JButton btn_batal) {
        this.btn_batal = btn_batal;
    }

    public JButton getBtn_bayar() {
        return btn_bayar;
    }

    public void setBtn_bayar(JButton btn_bayar) {
        this.btn_bayar = btn_bayar;
    }

    public JLabel getHarga_value() {
        return harga_value;
    }

    public void setHarga_value(JLabel harga_value) {
        this.harga_value = harga_value;
    }

    public JList<String> getList_barang() {
        return list_barang;
    }

    public void setList_barang(JList<String> list_barang) {
        this.list_barang = list_barang;
    }

    public JComboBox<String> getMetode_bayar() {
        return metode_bayar;
    }

    public void setMetode_bayar(JComboBox<String> metode_bayar) {
        this.metode_bayar = metode_bayar;
    }

    public JLabel getPembeli_value() {
        return pembeli_value;
    }

    public void setPembeli_value(JLabel pembeli_value) {
        this.pembeli_value = pembeli_value;
    }

    public JLabel getPenjual_value() {
        return penjual_value;
    }

    public void setPenjual_value(JLabel penjual_value) {
        this.penjual_value = penjual_value;
    }

    public JLabel getTgl_value() {
        return tgl_value;
    }

    public void setTgl_value(JLabel tgl_value) {
        this.tgl_value = tgl_value;
    }

    
}
